import { menuItems } from './menu-data';
import { asset } from './asset.js';
export function Content({request}) {
  return <>
    <section id="herkunft" className="origin section-pad">
      <div><p className="eyebrow">HERAT · AFGHANISTAN</p><h2>Ein Ursprung.<br/><em>Viele Möglichkeiten.</em></h2></div>
      <div className="origin-body"><p className="intro">Ganze Negin-Fäden aus Herat. Sorgfältig ausgewählt für die Gastronomie und den Handel.</p><p>Safran stammt aus den roten Narben von Crocus sativus. Jede Blüte trägt drei davon. Ihre feinen, getrockneten Fäden stehen im Mittelpunkt von Royal Spices.</p><div className="origin-facts"><div><b>Negin</b><span>Ganze Safranfäden</span></div><div><b>Grade 1</b><span>Produktangabe</span></div><div><b>Herat</b><span>Herkunft Afghanistan</span></div></div><p className="fineprint">Labor- und Herkunftsunterlagen zur angebotenen Lieferung erhalten Sie auf Anfrage. Wir klären mit Ihnen, auf welches Produkt und welche Charge sich die Nachweise beziehen.</p></div>
    </section>
    <section id="angebot" className="offering" aria-labelledby="offer-title">
      <div className="offer-heading"><p className="eyebrow">FÜR GASTRONOMIE & HANDEL</p><h2 id="offer-title">Für Ihre Karte.<br/><em>Für Ihr Sortiment.</em></h2><p>Für Bars, Cafés, Feinkost und den Einzelhandel. Im Glas für Ihre Küche oder für Ihre Kunden.</p><a className="text-link dark-link" href="#anfrage" onClick={()=>request('glaeser')}>Händlerangebot anfragen <span aria-hidden="true">↗</span></a></div>
      <div className="offer-facts"><dl><div><dt>Das aktuelle Angebot</dt><dd>1 g <span>im Glas</span></dd></div><div><dt>B2B-Preis · inklusive MwSt.</dt><dd>4,90 € <span>pro Glas</span></dd></div><div><dt>Für den Verkauf</dt><dd>24 Gläser <span>im Display</span></dd></div></dl><p className="fineprint">24er-Display: 117,60 € inkl. MwSt. Mindestbestellmenge, Verfügbarkeit, Lieferzeit und Versandkosten bestätigen wir in Ihrem individuellen Angebot.</p><p className="image-note">Die 3D-Ansicht und das Originalfoto zeigen die 0,5-g-Verpackung. Das aktuelle Angebot gilt für 1-g-Gläser.</p></div>
      <div className="product-gallery"><figure><img src={asset('display.webp')} width="1312" height="1199" loading="lazy" alt="Visualisierung des Royal-Spices-Thekendisplays mit 24 Gläsern à 1 g"/><figcaption>Das 24er-Display · Produktvisualisierung</figcaption></figure><figure><img src={asset('jars-real.webp')} width="1152" height="1536" loading="lazy" alt="Originalfoto der Royal-Spices-Gläser mit 0,5-g-Etikett"/><figcaption>Unsere Gläser · Originalaufnahme der 0,5-g-Ausführung</figcaption></figure></div>
      <div className="retail-note"><p>Für Ihre Küche zu Hause.</p><span>Privatkunden finden Füllmenge, aktuellen Preis und Versandkosten direkt im Shop.</span><a className="text-link" href="https://shop.tiktok.com/de/pdp/1729866250268023588?_t=ZG-9A03JNbD8iH">Zum TikTok Shop ↗</a></div>
    </section>
    <section id="grosshandel" className="wholesale section-pad">
      <div className="section-heading"><div><p className="eyebrow">LOSE WARE · AB 10 KG</p><h2>Im großen<br/><em>Maßstab.</em></h2></div><p>Sorte, Menge und Lieferkonditionen stimmen wir persönlich mit Ihnen ab.</p></div>
      <table><caption className="sr-only">Unverbindliche Kilopreise für losen Safran, Mindestmenge 10 kg</caption><thead><tr><th scope="col">Sorte</th><th scope="col">Richtpreis je kg</th><th scope="col">Mindestmenge</th></tr></thead><tbody>{[['Negin Safran','2.500 €'],['Pushal Safran','2.000 €'],['Konjai','400 €']].map(([n,p])=><tr key={n}><th scope="row">{n}</th><td>{p}</td><td>10 kg</td></tr>)}</tbody></table>
      <div className="trade-foot"><p className="fineprint">Unverbindliche Preisindikationen. Verfügbarkeit, Qualität, Umsatzsteuer, Versand und weitere Konditionen werden im individuellen Angebot bestätigt. Zertifikate und Laborberichte auf Anfrage.</p><a href="#anfrage" className="text-link" onClick={()=>request('grosshandel')}>Großhandel anfragen ↗</a></div>
    </section>
    <section id="catering" className="catering section-pad">
      <div className="catering-opening"><figure><img src={asset('catering.webp')} width="1200" height="1600" loading="lazy" alt="Royal Spices Catering bei einem Business-Event im AMG Brand Center Hamburg"/><figcaption>Business-Event · AMG Brand Center Hamburg</figcaption></figure><div><p className="eyebrow">CATERING · HAMBURG & UMGEBUNG</p><h2>Ihr Anlass.<br/><em>Unsere Handschrift.</em></h2><p className="intro">Persönlich geplant und vor Ort serviert. Sajad Akrami begleitet Sie als Inhaber und Koch.</p><p>Für Firmenveranstaltungen, Empfänge und private Anlässe. Für Meetings und Teams bieten wir auch Frühstück und Lunch als Office Catering.</p><a className="text-link" href="#anfrage" onClick={()=>request('catering')}>Catering anfragen ↗</a><a className="catalogue-link" href="https://royalspices.de/royal-spices-exklusiv-catering.pdf" target="_blank" rel="noreferrer">Exklusiv-Katalog als PDF ↗</a></div></div>
      <div className="menu-intro"><p className="eyebrow">AUS UNSEREM KATALOG</p><h3>Eine Auswahl für Ihren Anlass.</h3><p>Alle folgenden Speisenpreise enthalten die gesetzliche Mehrwertsteuer.</p></div>
      <div className="menu-list">{menuItems.map(item=><details key={item.title}><summary><span>{item.title}<small>{item.unit}</small></span><span>{item.price}<i aria-hidden="true">+</i></span></summary><div className="menu-detail"><p>{item.description}</p><ul>{item.dishes.map(([name,ingredients])=><li key={name}><b>{name}</b><span>{ingredients}</span></li>)}</ul><a className="text-link" href="#anfrage" onClick={()=>request('catering',item.title)}>{item.title} anfragen ↗</a></div></details>)}</div>
      <div className="packages"><article><p className="eyebrow">EMPFANG · 5 HAPPEN PRO GAST</p><h3>19,80 € <small>pro Person</small></h3><p>4 Signature Canapés · 1 Mini-Dessert</p><a className="text-link" href="#anfrage" onClick={()=>request('catering','Paket Empfang – 19,80 € pro Person')}>Empfang anfragen ↗</a></article><article><p className="eyebrow">EVENT · 9 HAPPEN PRO GAST</p><h3>36,90 € <small>pro Person</small></h3><p>3 Signature Canapés · 4 Löffelgerichte · 2 Mini-Desserts</p><a className="text-link" href="#anfrage" onClick={()=>request('catering','Paket Event – 36,90 € pro Person')}>Event anfragen ↗</a></article></div>
      <p className="fineprint">Paketpreise inkl. MwSt. Lieferung, Personal, Equipment, Dekoration sowie Auf- und Abbau werden separat angeboten. Auswahl und Mengen stimmen wir gemeinsam ab. Angaben zu Allergenen erhalten Sie zur gewählten Menüauswahl. Flying Buffet und Etageren: Zusammenstellung und Preis auf Anfrage.</p>
    </section>
    <section className="faq section-pad"><p className="eyebrow">GUT ZU WISSEN</p><h2>Ihre Fragen.</h2><details><summary>Gelten 10 kg Mindestabnahme auch für die Gläser?</summary><p>Die 10 kg gelten für lose Ware im Großhandel. Für die 1-g-Gläser nennen Sie uns Ihre gewünschte Stückzahl. Bestellbedingungen bestätigen wir im Angebot.</p></details><details><summary>Wie erhalte ich Qualitätsnachweise?</summary><p>Fordern Sie im Anfrageformular Labor- und Herkunftsunterlagen an. Wir klären, welche Nachweise für die konkret angebotene Lieferung vorliegen.</p></details><details><summary>Wie wird mein Catering kalkuliert?</summary><p>Termin, Ort, Gästezahl und Speisenauswahl bilden die Grundlage. Zusatzleistungen wie Personal, Lieferung und Equipment erhalten Sie separat im persönlichen Angebot.</p></details></section>
  </>;
}

